# Generated by Django 3.2.16 on 2023-11-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0003_alter_sat_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sat',
            old_name='order_number',
            new_name='rank',
        ),
    ]
