# Generated by Django 3.2.16 on 2023-11-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0004_rename_order_number_sat_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.CharField(max_length=100)),
                ('new_owner', models.CharField(max_length=100)),
                ('listed_price', models.FloatField(default=0)),
                ('satribut', models.CharField(max_length=50, verbose_name='Satribute')),
            ],
        ),
    ]
