# Generated by Django 3.2.16 on 2023-11-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0005_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='idx',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='satribut',
            field=models.FloatField(default=0),
        ),
    ]
