# Generated by Django 3.2.16 on 2023-11-20 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0006_auto_20231120_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sat_list.sat', verbose_name='Sat'),
        ),
    ]
