# Generated by Django 3.2.16 on 2023-11-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0007_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='satribut',
        ),
        migrations.AddField(
            model_name='transaction',
            name='satribute',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
