# Generated by Django 3.2.16 on 2023-11-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0008_auto_20231121_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='sat',
        ),
    ]
