# Generated by Django 3.2.16 on 2023-11-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0009_rename_category_transaction_sat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
    ]
