# Generated by Django 3.2.16 on 2023-11-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0010_remove_transaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(default='cd', max_length=100),
            preserve_default=False,
        ),
    ]
