# Generated by Django 3.2.16 on 2023-11-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0011_transaction_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sat',
            old_name='satribute',
            new_name='sat_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
    ]
