# Generated by Django 3.2.16 on 2023-11-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0012_auto_20231121_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sat_type',
            field=models.CharField(default='cd', max_length=100),
            preserve_default=False,
        ),
    ]
