# Generated by Django 3.2.16 on 2023-11-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0013_transaction_sat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='satribute',
            field=models.FloatField(default=0),
        ),
    ]
