# Generated by Django 3.2.16 on 2023-11-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0015_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sat',
            old_name='sat_type',
            new_name='satribute',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sat_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='satribute_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='satribute',
            field=models.CharField(max_length=100),
        ),
    ]
