# Generated by Django 3.2.16 on 2023-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0016_auto_20231122_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tokenid',
            field=models.CharField(default='cd', max_length=200),
            preserve_default=False,
        ),
    ]
