# Generated by Django 3.2.16 on 2023-11-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_list', '0018_bitcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='name',
            field=models.CharField(default='Bitcoin', max_length=50, verbose_name='Satribute'),
        ),
    ]
